#-----------------------------------------------------------------------------------
# Configuration for running the chatbot in evaluation mode.
# All values must be the same with the values from the training configuration.
#-----------------------------------------------------------------------------------
# - train_data_path         : The path to the txt file containing the training pairs
#                             in order to build the vocabulary.
# - checkpoint_path         : Path to the checkpoint containing the trained model.
# - embeddings_path         : Path to pre-trained embeddings file, i.e. GLoVe embeddings.
# - sampler                 : Decoder search sampler. The available samplers are: `greedy`,
#                             and `random`.
# - embedding_dim           : Dimensions of token embeddings.
# - padding_idx             : The PAD token index. Equal to 0.
# - hidden_size             : Hidden size of `rnn`, `gru` or `lstm` model.
# - dropout                 : Dropout value to apply after the `rnn`, `gru or `lstm`
# - num_layers              : Number of rnn layers in the encoder/decoder.
# - alignment_method        : Name of the alignment score method used in the attention layer.
#                             The available methods are: `concat`, `dot` and `general`.
#-----------------------------------------------------------------------------------
train_data_path: ./data/cornell-dialogs/assets/train_set.txt
checkpoint_path: ./checkpoints/base_model.pth
evaluation_parameters:
  embeddings_path:
  sampler: random
  embedding_init_params:
    embedding_dim: 128
    padding_idx: 0
  encoder_init_params:
    hidden_size: 128
    dropout: 0.1
    num_layers: 2
  decoder_init_params:
    alignment_method: dot
    hidden_size: 128
    dropout: 0.1
    num_layers: 2
